/** Textos del tablero corporativo de Dirección (D3), idénticos en web y móvil. */
export const corporateCopy = {
  title: "Tablero corporativo",
  description:
    "Compara centros y consolidado con las métricas registradas; baja de cada KPI al centro, canal o motor, servicio y OS.",
  executiveSummary: "Resumen ejecutivo",
  comparison: "Comparativo por centro",
  consolidated: "Consolidado",
  kpi: "KPI",
  previous: "Periodo anterior",
  /** Periodo anterior ya formateado (corporatePeriodLabel). */
  vsPrevious: (period: string) => `vs ${period}`,
  noComparison: "Sin comparativo",
  trendInvalid: {
    sin_historia: "Sin comparativo: algún centro no operaba desde el inicio del periodo anterior.",
    sin_base: "Sin comparativo: el periodo anterior fue 0.",
    sin_periodo: "Sin comparativo: no hay periodo anterior equivalente.",
  } as Record<string, string>,
  alertLow: (limit: string) => `Bajo el mínimo (${limit})`,
  alertHigh: (limit: string) => `Sobre el máximo (${limit})`,
  alertScope: { centro: "umbral del centro", organizacion: "umbral general" } as Record<string, string>,
  alerts: (n: number) => (n === 1 ? "1 alerta" : `${n} alertas`),
  forbidden: "Sin permiso para este KPI en los centros elegidos.",
  withoutAccess: (names: string) => `Sin permiso en: ${names}`,
  viewDetail: "Ver detalle",
  mixTitle: "Ranking de motores y servicios",
  byEngine: "Motores de ingreso",
  byService: "Servicios y productos",
  sortBy: "Ordenar por",
  sortRevenue: "Ingreso",
  sortMargin: "Margen",
  revenue: "Ingreso",
  margin: "Margen",
  marginPct: "Margen %",
  share: "Participación",
  quantity: "Unidades",
  reconciliation: "Conciliación con el estado de resultados",
  difference: "Diferencia",
  reconciled: "Cuadra con el P&L (diferencia 0)",
  notReconciled: (d: string) => `Diferencia contra el P&L: ${d}`,
  mixForbidden: "Sin permiso para ver ventas por motor y servicio en los centros elegidos.",
  mixEmpty: "Sin ventas en el periodo.",
  // Drill-down
  drillTitle: "Detalle del KPI",
  back: "Volver al tablero",
  sum: "Suma de filas",
  drillReconciled: "Las filas suman la cifra (diferencia 0).",
  drillDifference: (d: string) => `Diferencia contra la cifra: ${d}`,
  nonAdditive: "Promedio o tasa: cada fila aplica la misma fórmula a su subconjunto.",
  allCenters: "Consolidado de los centros elegidos",
  openMovements: "Ver movimientos",
  unknownCard: "El KPI no existe en el tablero.",
  noDetail: "Sin más detalle para este KPI.",
  orderLinesEmpty: "Sin órdenes de servicio en el periodo.",
  levelEmpty: "Sin datos en el periodo.",
  // Umbrales
  thresholds: "Umbrales de alerta",
  thresholdsHint:
    "Alerta visual cuando el KPI queda por debajo del mínimo o por encima del máximo. El umbral de un centro pisa al general. Sin notificaciones externas.",
  thresholdsReadOnly: "Los umbrales se consultan aquí y los cambia el admin corporativo en la web.",
  noThresholds: "No hay umbrales configurados.",
  card: "KPI",
  center: "Centro",
  allCentersOption: "Todos los centros (general)",
  min: "Mínimo",
  max: "Máximo",
  reason: "Motivo del cambio",
  save: "Guardar umbral",
  saved: "Umbral guardado",
  remove: "Quitar umbral",
  removed: "Umbral quitado",
  exportCsv: "Exportar CSV",
  shareCsv: "Compartir CSV",
  filtersNote:
    "Los filtros (centros y periodo) aplican igual a todas las tarjetas; canal y motor se eligen en el detalle.",
} as const;
