/** Textos de autenticación y sesión, idénticos en web y móvil. */
export const authCopy = {
  loginTitle: "Iniciar sesión",
  emailLabel: "Correo electrónico",
  passwordLabel: "Contraseña",
  submitLogin: "Entrar",
  forgotLink: "¿Olvidaste tu contraseña?",
  forgotTitle: "Recuperar contraseña",
  forgotHelp: "Te enviaremos un enlace para crear una nueva contraseña.",
  submitForgot: "Enviar enlace",
  forgotSent:
    "Si el correo está registrado, recibirás un enlace para restablecer tu contraseña. Revisa también tu carpeta de spam.",
  backToLogin: "Volver a iniciar sesión",
  resetTitle: "Nueva contraseña",
  newPasswordLabel: "Nueva contraseña",
  confirmPasswordLabel: "Confirmar contraseña",
  submitReset: "Guardar contraseña",
  resetDone: "Tu contraseña se actualizó.",
  logout: "Cerrar sesión",
  selectCenterTitle: "Elige un centro",
  selectCenterHelp:
    "Tienes acceso a varios centros. Elige con cuál vas a trabajar; puedes cambiarlo después.",
  changeCenter: "Cambiar centro",
  activeCenterLabel: "Centro activo",
  noCentersTitle: "Sin centros asignados",
  noCenters: "Tu cuenta aún no tiene centros asignados. Pide a un administrador que te agregue.",
  disabledTitle: "Cuenta deshabilitada",
  disabled: "Tu cuenta está deshabilitada. Si crees que es un error, contacta al administrador de tu centro.",
  forbiddenTitle: "Sin permiso",
  forbidden: "Tu rol en el centro activo no permite ver esta sección.",
  accountTitle: "Mi cuenta",
  teamTitle: "Equipo del centro",
  teamEmpty: "El centro aún no tiene miembros asignados.",
  editCenterTitle: "Editar centro",
  centerNameLabel: "Nombre del centro",
  timezoneLabel: "Zona horaria (IANA)",
  reasonLabel: "Motivo del cambio",
  submitEditCenter: "Guardar cambios",
  saved: "Cambios guardados.",
  errors: {
    invalidCredentials: "Correo o contraseña incorrectos.",
    emailNotConfirmed: "Confirma tu correo antes de iniciar sesión.",
    disabled: "Tu cuenta está deshabilitada.",
    rateLimited: "Demasiados intentos. Espera unos minutos e inténtalo de nuevo.",
    weakPassword: "La contraseña es demasiado débil.",
    samePassword: "La nueva contraseña debe ser distinta a la anterior.",
    sessionExpired: "Tu sesión o el enlace expiraron. Vuelve a intentarlo.",
    network: "No hay conexión con el servidor. Revisa tu red.",
    unknown: "Ocurrió un error inesperado. Inténtalo de nuevo.",
  },
} as const;
